In [1]:
import pandas as pd

In [7]:
df_appart=pd.read_csv("https://www.data.gouv.fr/fr/datasets/r/87038926-fb31-4959-b2ae-7a24321c599a", sep="|")

/tmp/ipykernel_253/4213222410.py:1: DtypeWarning: Columns (18,23,24,26,28,31,33,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df_appart=pd.read_csv("https://www.data.gouv.fr/fr/datasets/r/87038926-fb31-4959-b2ae-7a24321c599a", sep="|")

In [6]:
df_appart.sample(15)

,Code service sages,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
340647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13/05/2022,Vente,...,NaN,1,2.0,Appartement,NaN,50.0,2.0,NaN,NaN,NaN
439463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/03/2022,Vente,...,NaN,1,2.0,Appartement,NaN,25.0,2.0,NaN,NaN,NaN
346491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,24/02/2022,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,P,NaN,2364.0
926978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15/04/2022,Vente,...,NaN,0,1.0,Maison,NaN,120.0,6.0,S,NaN,538.0
752728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,08/02/2022,Vente,...,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
397702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,26/04/2022,Vente,...,NaN,2,2.0,Appartement,NaN,60.0,3.0,NaN,NaN,NaN
1246944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,01/02/2022,Vente,...,NaN,0,4.0,Local industriel. commercial ou assimilé,NaN,NaN,NaN,S,NaN,3947.0
1003629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,31/01/2022,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,172.0
1308719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14/02/2022,Vente,...,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
1415286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,05/04/2022,Vente,...,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
455311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/05/2022,Vente,...,NaN,2,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
1200234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,04/05/2022,Vente,...,NaN,2,2.0,Appartement,NaN,87.0,4.0,NaN,NaN,NaN
1347148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/06/2022,Vente,...,NaN,2,2.0,Appartement,NaN,54.0,2.0,NaN,NaN,NaN
1228189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,08/04/2022,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,T,NaN,256.0
385724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,27/01/2022,Vente,...,NaN,0,1.0,Maison,NaN,116.0,4.0,S,NaN,1285.0